language: generic 
sudo: required
service:
  - docker

before_install: 
  - docker build -t tae/docker-react -f Dockerfile.dev .
script: 
  - docker run -e CI=true wacharin-stack/docker-react npm run test