language: generic 
sudo: required
service:
  - docker

before_install: 
  - docker build -t wacharin-stack/docker-react -f Dockerfile.dev .
script: 
  - docker run -e CI=true wacharin-stack/docker-react npm run test
deploy: 
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: "docker"
  nv: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-northeast-1-822974034637"
  bucket_path: "docker"
  on
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
